networks:
  forgejo:
    external: false
  proxy:
    name: proxy 
    external: true

services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=3002
      - USER_GID=3002
      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=db:3306
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    restart: unless-stopped
    security_opt: 
      - no-new-privileges
    networks:
      - forgejo
      - proxy
    volumes:
      - /home/forgejo/data:/data
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "3000:3000"
#      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=forgejo
      - MYSQL_USER=forgejo
      - MYSQL_PASSWORD=forgejo
      - MYSQL_DATABASE=forgejo
    networks:
      - forgejo
    volumes:
      - /home/forgejo/mysql:/var/lib/mysql
    security_opt: 
      - no-new-privileges
