services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    group_add:
      - "3100"
#    user: 3004:3004
#    ports:
#      - 8096:8096/tcp
#      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/syncthing/data:/music:ro
#      - type: bind
#        source: /home/syncthing/data/music
#        target: /media
#        read_only: true

#      - type: bind
#        source: /path/to/media2
#        target: /media2
#        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
#      - type: bind
#        source: /path/to/fonts
#        target: /usr/local/share/fonts/custom
#        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://domain.ru
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    security_opt: 
      - no-new-privileges
    networks:
      proxy:

networks:
  proxy:
    name: proxy 
    external: true
