---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Закладки:

    - Github:
        - icon: github.png
          href: https://github.com/

    - Codeberg:
        - icon: codeberg.png
          href: https://codeberg.org/

    - Flathub:
        - icon: flathub.png
          href: https://flathub.org/

    - ARU:
        - icon: codeberg.png
          href: https://ventureo.codeberg.page/

    - Forum Sanohosting:
        - abbr: FS
          href: https://forum.samohosting.ru/

#    - Github:
#        - icon: github.png
#          href: https://github.com/

#- Social:
#    - Reddit:
#        - abbr: RE
#          href: https://reddit.com/

#- Entertainment:
#    - YouTube:
#        - abbr: YT
#          href: https://youtube.com/
