---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey
#background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
layout:

  Сервера:
    style: row
    columns: 4
  
  Сервисы:
    style: row
    columns: 5

  Закладки:
    style: row
    columns: 5

