services:
  searxng:
    container_name: searxng
    restart: unless-stopped
    networks:
      proxy: 
        #    ports:
        #      - 8888:8080
    volumes:
      - ./config/:/etc/searxng/
      - ./data/:/var/cache/searxng/
    image: docker.io/searxng/searxng:latest
networks:
  proxy:
    external: true
